# Generated by Django 4.0.5 on 2022-06-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.IntegerField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(max_length=300)),
                ('sent_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
